### PR TITLE
Fixed styling issues of Timeline component

### LINKED ISSUE #46: Fix timeline styling
The timeline that is shown under the visualization is not properly responsive. On desktops, it doesn't span the entire width, and on mobile devices, it is too wide, resulting in weird wrapping behavior that makes it block part of the blockchain visualization.

image

image

### PR DESCRIPTION
**Pull request by naiknareshh**
Fixed and tested styling issue for the timeline component on Laptop and Mobile devices. Fixes #46

### CODE REVIEW

**Comment by atjn** [comment]
Hello @naiknareshh, thank you for working on this!

I don't have time to review your PR right now, but I will be back soon. Until then, I can see that your code is not properly formatted, which is also why the tests are failing. We use [editorconfig](https://editorconfig.org/) to automatically configure our editors, so that they always write the code in the format we want. You can see our configuration in the [`.editorconfig`](https://github.com/atjn/blockchain-visualizer/blob/main/.editorconfig) file.
Most editors have a plugin that will detect an editorconfig file and automatically use the correct settings. I would suggest finding a plugin like that for your editor :)

Also a quick tip: if you write "Fixes #46" instead of "Issue #46" in the description of your pull request, then it will be linked back to the issue I created, and will automagically close the issue when we merge this.

**Comment by atjn** [comment]
Apart from the formatting issues, everything seems great. I will do a final check when you fix the formatting :)

**Comment by naiknareshh** [comment]
I think my prettier setup in VS code updated the entire style.css file in my last PR, I have reverted those changes and will work on the formatting as soon as I get some bandwidth. apologies

**Comment by atjn** [comment]
You're welcome to do as you please, but I don't think you needed to delete all the changes you made. If you run `npm run lint`, it should be able to revert most of the changes that Prettier made, and if you go to the [files changed](https://github.com/atjn/blockchain-visualizer/pull/55/files) tab, it will show you all the changes that you made, and you will be able to quickly fix the few formatting mistakes that might be left, while retaining the code you worked on. (it doesn't show anything right now because you deleted all your changes)

**Comment by naiknareshh** [comment]
Hi @atjn didn't know `npm run lint` would fix the issue. thanks for the comment, I will take remember this as a learning for future PRs. Thanks again!

**Pull request closed without merging**
